name: tradedex
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 2.1.0+55

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  strings: ^0.1.0
  shared_preferences: ^0.4.3
  firebase: ^5.0.4
  firebase_auth: ^0.14.0+5
  firebase_core: ^0.4.0+9
  firebase_database: ^3.0.7
  cloud_firestore: ^0.12.9+3
  google_sign_in: ^4.0.7
  rxdart: ^0.22.2
  url_launcher: ^4.0.3
  preferences: ^1.1.0
  package_info: ^0.4.0+1
  material_design_icons_flutter: ^3.1.3493
  property_change_notifier: ^0.2.0
  clipboard_manager: ^0.0.4
  firebase_storage: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  image_path: "logo/tradedex_logo-small-white.png"
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - logo/
    - icon/
    - types2/
    - collection/
    - json/
    - json/languages/
    - json/official_collections/
    - json/individual_collections/
    - assets_bundle/pokemon_icons_unown/
    - assets_bundle/pokemon_icons_blank/
    - assets_bundle/pokemon_icons_event/
    - assets_bundle/pokemon_icons_alolan/
    - assets_bundle/pokemon_icons_spinda/
    - assets_bundle/pokemon_icons_regional/
    - assets_bundle/pokemon_icons_shiny/
    - assets_bundle/pokemon_icons_galarian/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
